import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { db, pool, DATABASE_URL } from './client.js';

/**
 * Applies the versioned SQL migrations in `./drizzle` (generated by
 * `drizzle-kit generate`). Run via `npm run db:migrate` locally, and as the
 * first step of the Docker entrypoint before the server starts serving.
 */
async function main() {
  console.log(`[migrate] applying migrations to ${DATABASE_URL}`);
  await migrate(db, { migrationsFolder: 'drizzle' });
  console.log('[migrate] done');
  await pool.end();
}

main().catch((err) => {
  console.error('[migrate] failed', err);
  process.exit(1);
});
